version: "3.9"

services:
  app_db:
    container_name: app_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pokemon
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - app_db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: app_db
      MYSQL_ROOT_PASSWORD: password

  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
      - '8080:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs

volumes:
  db:
